Cloudwatch shipper - basic
logzio/cloudwatch-shipper pull request #1
Opened 2022-10-25 15:39 UTC by mirii1994

This is the initial code for the Cloudwatch shipper.

2022-10-25 20:33 UTC, Doron-Bargo requested changes
Please see my comments

2022-10-25 20:33 UTC, Doron-Bargo commented on main.go
> +	sugLog.Info("Finished lambda run, draining Logzio Sender")
You are not really drain as you send data to logziosender

2022-10-26 07:24 UTC, mirii1994 commented on README.md
> +| `logGroupName`     | The name of log group you want to ship logs from to Logz.io                                                                                       | **Required**     |
This parameter goes to the Cloudformation template to add as a trigger, not to the code itself.
At the moment, there's no way to dynamically create triggers, only hard coded.
So the Cloudformation template creates only one trigger. We'll create another Lambda that adds triggers, and there they'll be able to insert multiple logs.

2022-10-26 07:31 UTC, mirii1994 commented on cloudformation/sam-template.yaml
> +        Key: cloudwatch-shipper/0.0.1/function.zip
This is the version number I give for every new project. What version number you want?

2022-10-26 07:33 UTC, mirii1994 commented on main.go
> +	sugLog.Info("Finished lambda run, draining Logzio Sender")
In line 30 theres a `defer logzioSender.Drain()` command, it will drain the logzioSender at the end of the `HandleRequest` func :)

2022-10-31 09:47 UTC, nico-shishkin approved these changes

2022-11-02 08:39 UTC, Doron-Bargo requested changes
Good work please see my comments

2022-11-03 20:43 UTC, Doron-Bargo requested changes
Please see my comments

2022-11-03 20:43 UTC, Doron-Bargo commented on logs_processor/sender.go
> +	var compressedBuf bytes.Buffer
please check the size of the message before compressing it so our listener can handle it

2022-11-03 20:43 UTC, Doron-Bargo commented on logs_processor/sender.go
> +	case http.StatusUnauthorized:
If you get unauthorized its mean the token is incorrect . Let put more informative message

2022-11-06 09:32 UTC, mirii1994 commented on logs_processor/logs_processor.go
> +func handleMessageField(logzioLog map[string]interface{}, messageField string) {
Eventually it will be a json. What I meant is that if it's not a json - it will appear as a string under the field message.

2022-11-06 10:25 UTC, Doron-Bargo commented on logs_processor/logs_processor.go
> +func handleMessageField(logzioLog map[string]interface{}, messageField string) {
ok cool

2022-11-14 06:38 UTC, Doron-Bargo approved these changes
lgtm

2022-11-14 08:18 UTC, merged